# Generated by Django 3.0.7 on 2020-06-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_func', '0004_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
    ]
