# Generated by Django 3.0.5 on 2020-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(max_length=10)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('directors', models.CharField(blank=True, max_length=100, null=True)),
                ('casts', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
