# Generated by Django 3.0.5 on 2020-06-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_moviecomment_movieupdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
