# Generated by Django 3.0.5 on 2020-06-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_moviecommentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
