# Generated by Django 3.0.5 on 2020-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_auto_20200616_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
