# Generated by Django 3.0.5 on 2020-06-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0008_auto_20200617_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
