# Generated by Django 3.0.5 on 2020-06-18 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0009_auto_20200617_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecommentreport',
            name='movieComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Movie.MovieComment'),
        ),
    ]
