# Generated by Django 3.0.5 on 2020-06-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0010_auto_20200618_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieupdown',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
    ]
