# Generated by Django 3.0.5 on 2020-06-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0011_movieupdown_down_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieupdown',
            name='down_count',
        ),
        migrations.RemoveField(
            model_name='movieupdown',
            name='movie',
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movieupdown',
            name='moviecomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.MovieComment'),
        ),
    ]
