# Generated by Django 3.0.5 on 2020-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20200614_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
