# Generated by Django 3.0.5 on 2020-06-17 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Book', '0004_auto_20200617_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=256)),
                ('state', models.IntegerField(default=0)),
                ('reportTime', models.DateTimeField(auto_now_add=True)),
                ('bookComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.BookComment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
