# Generated by Django 3.0.5 on 2020-06-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_bookcommentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.URLField(default=''),
        ),
    ]
