# Generated by Django 3.0.5 on 2020-06-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20200617_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookupdown',
            name='book',
        ),
        migrations.AddField(
            model_name='bookupdown',
            name='bookcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Book.BookComment'),
        ),
        migrations.AlterField(
            model_name='bookcommentreport',
            name='bookComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Book.BookComment'),
        ),
    ]
