# Generated by Django 3.0.5 on 2020-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20200619_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomment',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
    ]
